### ISSUE TITLE
Funktion für's abbrechen von gestarteten Raids

### ISSUE THREAD

**Issue by paddi0010** [zion-networks/BetterRaid#1]
### Hätte einen Vorschlag, der finde ich in solch ein Programm unbedingt vorhanden sein sollte. 

Man könnte eine Möglichkeit einbauen einen bereits gestarteten Raid abbrechen zu können, falls man sich verklickt hat. 

#### Wie man das umsetzen könnte:

- Mit einem Window, welches einen Button "Raid abbrechen", sowie eine Leiste oder einem Timer wann der Raid durch ist, enthält, wenn der Raid erfolgreich gestartet wurde. Bevor das aber passiert, könnte eine abfrage kommen, ob man den Raid wirklich starten möchte.
- Wenn ein Raid erfolgreich abgebrochen wurde, könnte ein bestätigungs Fenster kommen, wenn nicht, ein Hinweis, dass der Raid nicht abgebrochen werden konnte und durchgeführt wird.

**Comment by WeboGraph** [comment]
Machen kann man so etwas doch über den `/unraid` Befehl machen.

**Comment by AedDev** [comment]
> Machen kann man so etwas doch über den `/unraid` Befehl machen.

Das ist richtig, raiden kann man aber auch per `/raid <channel>` command - und der Sinn von BetterRaid ist ja in diesem Sinne, dass man ein all-in-one Tool hat, dass das Raiden zu anderen Kanaelen vereinfachen soll.

**Comment by paddi0010** [comment]
> Machen kann man so etwas doch über den `/unraid` Befehl machen.

Das Programm soll ja, wie bereits AedDev erwähnt hat, ein All-in-One Tool sein, welches das Raiden besser verwaltbar machen soll. 

Wenn man aber nach deinem Argument geht, könnte man ja direkt über den Chat jemanden raiden bzw. diesen abbrechen und das Programm wäre überflüssig. Das ist jedoch etwas nervig, da man ständig in den Chat wechseln müsste, nur um den Raid zu verwalten und genau da setzt das Tool an. 

Daher wäre diese Funktion durchaus sinnvoll und eine Überlegung wert, da es mal vorkommen kann, dass man sich verklickt, vor allem bei einer längeren Liste. 😃

**Comment by WeboGraph** [comment]
Leute, das war ein Vorschlag und bezog sich darauf, dass wenn die Helix Library keinen Cancel anbietet, dass man schnell eine IRC Verbindung im Hintergrund aufmacht und den `/unraid` Command auf dem eigenen Channel absetzt. Es geht ja einfacher, in dem einen DELETE Request auf den Endpunkt ´/raid´ macht.

**Comment by AedDev** [comment]
> Leute, das war ein Vorschlag und bezog sich darauf, dass wenn die Helix Library keinen Cancel anbietet, dass man schnell eine IRC Verbindung im Hintergrund aufmacht und den `/unraid` Command auf dem eigenen Channel absetzt. Es geht ja einfacher, in dem einen DELETE Request auf den Endpunkt ´/raid´ macht.

Das hattest du in deinem vorangehenden Kommentar so nicht gesagt gehabt, weshalb es so interpretiert wurde :) Aber um den fachlichen Part anzusprechen: Helix hat einen entsprechenden Endpoint.

Siehe hier: https://github.com/zion-networks/BetterRaid/blob/8a10573fbfaabaa9cc09ab111b8baa0aec43064c/Services/Implementations/TwitchDataService.cs#L145
