### ISSUE TITLE
[Feature Request] Settings Screen

### ISSUE THREAD

**Issue by AedDev** [zion-networks/BetterRaid#19]
Implement a settings screen to allow the user to change various settings. For example:

- From #2: Manage categories for channel suggestions, white/-blacklist for tags
- From #6: Default poll time for raid target polls
- From #8: Enable / Disable visibility of the logged in user's viewer count
- From #13: Enable / Disable auto-visit when raiding a channel
- From #18: Change app language
- From #20: Enable / Disable Dark-Mode

**Comment by phlphil** [comment]
- Light or Dark Mode (with system default detection)

**Comment by AedDev** [comment]
Resolved with PR #31
