### ISSUE TITLE
[Bug] Invalid OAuth Link

### ISSUE THREAD

**Issue by PurpurTentakel97** [zion-networks/BetterRaid#4]
When I click the Twitch button to autositze myself the resulting Twitch page has an Issue.

Resulting link: `https://id.twitch.tv/oauth2/authorize?client_id=kkxu4jorjrrc5jch1ito5i61hbev2o^&redirect_uri=http://localhost:9900^&response_type=token^&scope=channel:manage:raids+user:read:subscriptions` 

Affected Browser: Opera GX on Windows

Displayed content: 
```
{
  "status": 400,
  "message": "invalid client"
}
```
Console:
![image](https://github.com/user-attachments/assets/7601f899-b33c-4830-99de-2a487fe30bce)

Have fun. :)

**Comment by AedDev** [comment]
Will be fixed in 0.0.3-alpha
