### ISSUE TITLE
[Feature Request] - Zuschauerzahl ausblenden

### ISSUE THREAD

**Issue by paddi0010** [zion-networks/BetterRaid#8]
Es wäre cool, wenn es eine Option gibt die Zuschauerzahl **vom Streamer** ausblenden zu können.

### Wie man das machen könnte:

- Mit einen kleinen Button, neben der Zuschauerzahl
- Mit einen klick auf die Zuschauerzahl, die nach den klick ausgeblendet wird, wenn erneut drauf geklickt wird, soll diese wieder eingeblendet werden.

Da das ein kleines "Feature" ist, muss es nicht zwingend in der nächsten Alpha Version drinne sein. ;)

**Comment by AedDev** [comment]
Implemented with #31
